package com.example.myspendings.ui.theme

import android.app.Activity
import android.os.Build
import androidx.appcompat.app.AppCompatActivity
import com.example.myspendings.R

// This project uses View-based UI. 
// Compose theme file was likely generated by a template and is not needed.
// Removing Compose-specific code to resolve compilation errors.
